export type CategoryType =
  | "correctness"
  | "style"
  | "pedantic"
  | "suspicious"
  | "perf"
  | "restriction"
  | "nursery";

export interface Category {
  ruleName: string;
  source: string;
  category: CategoryType;
}

export const Categories: Record<string, Category> = {
  "accessor-pairs": { ruleName: "accessor-pairs", source: "eslint", category: "pedantic" },
  "adjacent-overload-signatures": {
    ruleName: "adjacent-overload-signatures",
    source: "typescript",
    category: "style",
  },
  "alt-text": { ruleName: "alt-text", source: "jsx_a11y", category: "correctness" },
  "anchor-ambiguous-text": {
    ruleName: "anchor-ambiguous-text",
    source: "jsx_a11y",
    category: "restriction",
  },
  "anchor-has-content": {
    ruleName: "anchor-has-content",
    source: "jsx_a11y",
    category: "correctness",
  },
  "anchor-is-valid": { ruleName: "anchor-is-valid", source: "jsx_a11y", category: "correctness" },
  "api-breakage/cancel-waterfall": {
    ruleName: "cancel-waterfall",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/disallowed-definition-imports": {
    ruleName: "disallowed-definition-imports",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/no-global-value": {
    ruleName: "no-global-value",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/no-top-level-await": {
    ruleName: "no-top-level-await",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/prefer-cjs-exports": {
    ruleName: "prefer-cjs-exports",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/prefer-cjs-imports": {
    ruleName: "prefer-cjs-imports",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/prefer-esm-exports": {
    ruleName: "prefer-esm-exports",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/prefer-esm-imports": {
    ruleName: "prefer-esm-imports",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/use-cjs-extension": {
    ruleName: "use-cjs-extension",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/use-esm-extension": {
    ruleName: "use-esm-extension",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/use-node-protocol": {
    ruleName: "use-node-protocol",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/use-win32-registry": {
    ruleName: "use-win32-registry",
    source: "api-breakage",
    category: "correctness",
  },
  "api-breakage/wasm-metafield": {
    ruleName: "wasm-metafield",
    source: "api-breakage",
    category: "correctness",
  },
  "approx-constant": { ruleName: "approx-constant", source: "oxc", category: "suspicious" },
  "aria-activedescendant-has-tabindex": {
    ruleName: "aria-activedescendant-has-tabindex",
    source: "jsx_a11y",
    category: "correctness",
  },
  "aria-props": { ruleName: "aria-props", source: "jsx_a11y", category: "correctness" },
  "aria-proptypes": { ruleName: "aria-proptypes", source: "jsx_a11y", category: "correctness" },
  "aria-role": { ruleName: "aria-role", source: "jsx_a11y", category: "correctness" },
  "aria-unsupported-elements": {
    ruleName: "aria-unsupported-elements",
    source: "jsx_a11y",
    category: "correctness",
  },
  "array-callback-return": {
    ruleName: "array-callback-return",
    source: "eslint",
    category: "pedantic",
  },
  "array-type": { ruleName: "array-type", source: "typescript", category: "style" },
  "arrow-body-style": { ruleName: "arrow-body-style", source: "eslint", category: "style" },
  "attr-case": { ruleName: "attr-case", source: "html", category: "style" },
  "attr-name-case": { ruleName: "attr-name-case", source: "html", category: "style" },
  "attr-no-duplication": {
    ruleName: "attr-no-duplication",
    source: "html",
    category: "correctness",
  },
  "autocomplete-valid": {
    ruleName: "autocomplete-valid",
    source: "jsx_a11y",
    category: "correctness",
  },
  "avoid-new": { ruleName: "avoid-new", source: "promise", category: "style" },
  "await-thenable": { ruleName: "await-thenable", source: "typescript", category: "correctness" },
  "bad-array-method-on-arguments": {
    ruleName: "bad-array-method-on-arguments",
    source: "oxc",
    category: "correctness",
  },
  "bad-bitwise-operator": {
    ruleName: "bad-bitwise-operator",
    source: "oxc",
    category: "restriction",
  },
  "bad-char-at-comparison": {
    ruleName: "bad-char-at-comparison",
    source: "oxc",
    category: "correctness",
  },
  "bad-comparison-sequence": {
    ruleName: "bad-comparison-sequence",
    source: "oxc",
    category: "correctness",
  },
  "bad-min-max-func": { ruleName: "bad-min-max-func", source: "oxc", category: "correctness" },
  "bad-object-literal-comparison": {
    ruleName: "bad-object-literal-comparison",
    source: "oxc",
    category: "correctness",
  },
  "bad-replace-all-arg": {
    ruleName: "bad-replace-all-arg",
    source: "oxc",
    category: "correctness",
  },
  "ban-ts-comment": { ruleName: "ban-ts-comment", source: "typescript", category: "pedantic" },
  "ban-tslint-comment": { ruleName: "ban-tslint-comment", source: "typescript", category: "style" },
  "ban-types": { ruleName: "ban-types", source: "typescript", category: "pedantic" },
  "block-scoped-var": { ruleName: "block-scoped-var", source: "eslint", category: "suspicious" },
  "branches-sharing-code": {
    ruleName: "branches-sharing-code",
    source: "oxc",
    category: "nursery",
  },
  "button-has-type": { ruleName: "button-has-type", source: "react", category: "restriction" },
  "capitalized-comments": { ruleName: "capitalized-comments", source: "eslint", category: "style" },
  "catch-error-name": { ruleName: "catch-error-name", source: "unicorn", category: "style" },
  "catch-or-return": { ruleName: "catch-or-return", source: "promise", category: "restriction" },
  "check-access": { ruleName: "check-access", source: "jsdoc", category: "restriction" },
  "check-property-names": {
    ruleName: "check-property-names",
    source: "jsdoc",
    category: "correctness",
  },
  "check-tag-names": { ruleName: "check-tag-names", source: "jsdoc", category: "correctness" },
  "checked-requires-onchange-or-readonly": {
    ruleName: "checked-requires-onchange-or-readonly",
    source: "react",
    category: "pedantic",
  },
  "class-literal-property-style": {
    ruleName: "class-literal-property-style",
    source: "typescript",
    category: "style",
  },
  "class-methods-use-this": {
    ruleName: "class-methods-use-this",
    source: "eslint",
    category: "restriction",
  },
  "click-events-have-key-events": {
    ruleName: "click-events-have-key-events",
    source: "jsx_a11y",
    category: "correctness",
  },
  complexity: { ruleName: "complexity", source: "eslint", category: "restriction" },
  "consistent-assert": { ruleName: "consistent-assert", source: "unicorn", category: "pedantic" },
  "consistent-date-clone": {
    ruleName: "consistent-date-clone",
    source: "unicorn",
    category: "style",
  },
  "consistent-empty-array-spread": {
    ruleName: "consistent-empty-array-spread",
    source: "unicorn",
    category: "pedantic",
  },
  "consistent-existence-index-check": {
    ruleName: "consistent-existence-index-check",
    source: "unicorn",
    category: "style",
  },
  "consistent-function-scoping": {
    ruleName: "consistent-function-scoping",
    source: "unicorn",
    category: "suspicious",
  },
  "consistent-generic-constructors": {
    ruleName: "consistent-generic-constructors",
    source: "typescript",
    category: "style",
  },
  "consistent-indexed-object-style": {
    ruleName: "consistent-indexed-object-style",
    source: "typescript",
    category: "style",
  },
  "consistent-return": { ruleName: "consistent-return", source: "typescript", category: "nursery" },
  "consistent-test-it": { ruleName: "consistent-test-it", source: "jest", category: "style" },
  "consistent-type-assertions": {
    ruleName: "consistent-type-assertions",
    source: "typescript",
    category: "style",
  },
  "consistent-type-definitions": {
    ruleName: "consistent-type-definitions",
    source: "typescript",
    category: "style",
  },
  "consistent-type-exports": {
    ruleName: "consistent-type-exports",
    source: "typescript",
    category: "nursery",
  },
  "consistent-type-imports": {
    ruleName: "consistent-type-imports",
    source: "typescript",
    category: "style",
  },
  "consistent-type-specifier-style": {
    ruleName: "consistent-type-specifier-style",
    source: "import",
    category: "style",
  },
  "consistent-vitest-vi": { ruleName: "consistent-vitest-vi", source: "vitest", category: "style" },
  "const-comparisons": { ruleName: "const-comparisons", source: "oxc", category: "correctness" },
  "constructor-super": { ruleName: "constructor-super", source: "eslint", category: "correctness" },
  curly: { ruleName: "curly", source: "eslint", category: "style" },
  "custom-error-definition": {
    ruleName: "custom-error-definition",
    source: "unicorn",
    category: "style",
  },
  default: { ruleName: "default", source: "import", category: "correctness" },
  "default-case": { ruleName: "default-case", source: "eslint", category: "restriction" },
  "default-case-last": { ruleName: "default-case-last", source: "eslint", category: "style" },
  "default-param-last": { ruleName: "default-param-last", source: "eslint", category: "style" },
  "define-emits-declaration": {
    ruleName: "define-emits-declaration",
    source: "vue",
    category: "style",
  },
  "define-props-declaration": {
    ruleName: "define-props-declaration",
    source: "vue",
    category: "style",
  },
  "define-props-destructuring": {
    ruleName: "define-props-destructuring",
    source: "vue",
    category: "style",
  },
  "did-you-mean": { ruleName: "did-you-mean", source: "regex", category: "correctness" },
  "display-name": { ruleName: "display-name", source: "react", category: "pedantic" },
  "doctype-html5": { ruleName: "doctype-html5", source: "html", category: "correctness" },
  "double-comparisons": { ruleName: "double-comparisons", source: "oxc", category: "correctness" },
  "elem-behind-aria-encapsulation": {
    ruleName: "elem-behind-aria-encapsulation",
    source: "oxc",
    category: "nursery",
  },
  "empty-brace-spaces": { ruleName: "empty-brace-spaces", source: "unicorn", category: "style" },
  "empty-tags": { ruleName: "empty-tags", source: "jsdoc", category: "restriction" },
  "erasing-op": { ruleName: "erasing-op", source: "oxc", category: "correctness" },
  "error-message": { ruleName: "error-message", source: "unicorn", category: "style" },
  "escape-case": { ruleName: "escape-case", source: "unicorn", category: "pedantic" },
  "exhaustive-deps": { ruleName: "exhaustive-deps", source: "react", category: "correctness" },
  "explicit-length-check": {
    ruleName: "explicit-length-check",
    source: "unicorn",
    category: "pedantic",
  },
  "explicit-function-return-type": {
    ruleName: "explicit-function-return-type",
    source: "typescript",
    category: "restriction",
  },
  "explicit-module-boundary-types": {
    ruleName: "explicit-module-boundary-types",
    source: "typescript",
    category: "restriction",
  },
  export: { ruleName: "export", source: "import", category: "nursery" },
  "exports-last": { ruleName: "exports-last", source: "import", category: "style" },
  "extends-reassign": { ruleName: "extends-reassign", source: "eslint", category: "correctness" },
  fclosure: { ruleName: "fclosure", source: "oxc", category: "nursery" },
  "filename-case": { ruleName: "filename-case", source: "unicorn", category: "style" },
  first: { ruleName: "first", source: "import", category: "style" },
  "for-direction": { ruleName: "for-direction", source: "eslint", category: "correctness" },
  "forbid-dom-props": { ruleName: "forbid-dom-props", source: "react", category: "restriction" },
  "forbid-elements": { ruleName: "forbid-elements", source: "react", category: "restriction" },
  "forward-ref-uses-ref": {
    ruleName: "forward-ref-uses-ref",
    source: "react",
    category: "correctness",
  },
  "func-names": { ruleName: "func-names", source: "eslint", category: "style" },
  "func-style": { ruleName: "func-style", source: "eslint", category: "style" },
  "getter-return": { ruleName: "getter-return", source: "eslint", category: "nursery" },
  "global-require": { ruleName: "global-require", source: "node", category: "style" },
  "google-font-display": {
    ruleName: "google-font-display",
    source: "nextjs",
    category: "correctness",
  },
  "google-font-preconnect": {
    ruleName: "google-font-preconnect",
    source: "nextjs",
    category: "correctness",
  },
  "grouped-accessor-pairs": {
    ruleName: "grouped-accessor-pairs",
    source: "eslint",
    category: "style",
  },
  "group-exports": { ruleName: "group-exports", source: "import", category: "style" },
  "guard-for-in": { ruleName: "guard-for-in", source: "eslint", category: "style" },
  "handle-callback-err": {
    ruleName: "handle-callback-err",
    source: "node",
    category: "restriction",
  },
  "heading-has-content": {
    ruleName: "heading-has-content",
    source: "jsx_a11y",
    category: "correctness",
  },
  "hoisted-apis-on-top": {
    ruleName: "hoisted-apis-on-top",
    source: "vitest",
    category: "correctness",
  },
  "html-has-lang": { ruleName: "html-has-lang", source: "jsx_a11y", category: "correctness" },
  "html-lang-quotes": { ruleName: "html-lang-quotes", source: "html", category: "correctness" },
  "html-quotes": { ruleName: "html-quotes", source: "html", category: "style" },
  "id-denylist": { ruleName: "id-denylist", source: "eslint", category: "restriction" },
  "id-length": { ruleName: "id-length", source: "eslint", category: "style" },
  "id-match": { ruleName: "id-match", source: "eslint", category: "restriction" },
  "iframe-has-title": { ruleName: "iframe-has-title", source: "jsx_a11y", category: "correctness" },
  "img-redundant-alt": {
    ruleName: "img-redundant-alt",
    source: "jsx_a11y",
    category: "correctness",
  },
  "implements-on-classes": {
    ruleName: "implements-on-classes",
    source: "jsdoc",
    category: "correctness",
  },
  "implicit-anchors-prefer-button": {
    ruleName: "implicit-anchors-prefer-button",
    source: "oxc",
    category: "nursery",
  },
  "implicit-arrow-linebreak": {
    ruleName: "implicit-arrow-linebreak",
    source: "eslint",
    category: "style",
  },
  import: { ruleName: "import", source: "regex", category: "correctness" },
  "import/no-unresolved": { ruleName: "no-unresolved", source: "import", category: "correctness" },
  indent: { ruleName: "indent", source: "html", category: "style" },
  "indent-last": { ruleName: "indent-last", source: "html", category: "style" },
  indentation: { ruleName: "indentation", source: "eslint", category: "style" },
  "index-attr-quotes": { ruleName: "index-attr-quotes", source: "html", category: "correctness" },
  "init-declarations": { ruleName: "init-declarations", source: "eslint", category: "style" },
  "inline-script-id": { ruleName: "inline-script-id", source: "nextjs", category: "correctness" },
  "inline-script-placement": {
    ruleName: "inline-script-placement",
    source: "oxc",
    category: "nursery",
  },
  "jsx-boolean-value": { ruleName: "jsx-boolean-value", source: "react", category: "style" },
  "jsx-child-element-spacing": {
    ruleName: "jsx-child-element-spacing",
    source: "oxc",
    category: "nursery",
  },
  "jsx-closing-bracket-location": {
    ruleName: "jsx-closing-bracket-location",
    source: "eslint",
    category: "style",
  },
  "jsx-closing-tag-location": {
    ruleName: "jsx-closing-tag-location",
    source: "eslint",
    category: "style",
  },
  "jsx-curly-brace-presence": {
    ruleName: "jsx-curly-brace-presence",
    source: "react",
    category: "style",
  },
  "jsx-curly-spacing": { ruleName: "jsx-curly-spacing", source: "eslint", category: "style" },
  "jsx-filename-extension": {
    ruleName: "jsx-filename-extension",
    source: "react",
    category: "restriction",
  },
  "jsx-first-prop-new-line": {
    ruleName: "jsx-first-prop-new-line",
    source: "eslint",
    category: "style",
  },
  "jsx-fragments": { ruleName: "jsx-fragments", source: "react", category: "style" },
  "jsx-handler-names": { ruleName: "jsx-handler-names", source: "react", category: "style" },
  "jsx-key": { ruleName: "jsx-key", source: "react", category: "correctness" },
  "jsx-max-depth": { ruleName: "jsx-max-depth", source: "react", category: "style" },
  "jsx-max-props-per-line": {
    ruleName: "jsx-max-props-per-line",
    source: "eslint",
    category: "style",
  },
  "jsx-newline": { ruleName: "jsx-newline", source: "eslint", category: "style" },
  "jsx-no-comment-textnodes": {
    ruleName: "jsx-no-comment-textnodes",
    source: "react",
    category: "suspicious",
  },
  "jsx-no-constructed-context-values": {
    ruleName: "jsx-no-constructed-context-values",
    source: "react",
    category: "perf",
  },
  "jsx-no-duplicate-props": {
    ruleName: "jsx-no-duplicate-props",
    source: "react",
    category: "correctness",
  },
  "jsx-no-jsx-as-prop": { ruleName: "jsx-no-jsx-as-prop", source: "react_perf", category: "perf" },
  "jsx-no-new-array-as-prop": {
    ruleName: "jsx-no-new-array-as-prop",
    source: "react_perf",
    category: "perf",
  },
  "jsx-no-new-function-as-prop": {
    ruleName: "jsx-no-new-function-as-prop",
    source: "react_perf",
    category: "perf",
  },
  "jsx-no-new-object-as-prop": {
    ruleName: "jsx-no-new-object-as-prop",
    source: "react_perf",
    category: "perf",
  },
  "jsx-no-script-url": { ruleName: "jsx-no-script-url", source: "react", category: "suspicious" },
  "jsx-no-target-blank": { ruleName: "jsx-no-target-blank", source: "react", category: "pedantic" },
  "jsx-no-unescaped-entities": {
    ruleName: "jsx-no-unescaped-entities",
    source: "react",
    category: "pedantic",
  },
  "jsx-no-undef": { ruleName: "jsx-no-undef", source: "react", category: "correctness" },
  "jsx-no-useless-fragment": {
    ruleName: "jsx-no-useless-fragment",
    source: "react",
    category: "pedantic",
  },
  "jsx-one-instance-per-line": {
    ruleName: "jsx-one-instance-per-line",
    source: "oxc",
    category: "nursery",
  },
  "jsx-pascal-case": { ruleName: "jsx-pascal-case", source: "react", category: "style" },
  "jsx-props-no-spreading": {
    ruleName: "jsx-props-no-spreading",
    source: "react",
    category: "style",
  },
  "jsx-props-no-spread-multi": {
    ruleName: "jsx-props-no-spread-multi",
    source: "react",
    category: "correctness",
  },
  "jsx-self-closing-comp": {
    ruleName: "jsx-self-closing-comp",
    source: "eslint",
    category: "style",
  },
  "jsx-sort-props": { ruleName: "jsx-sort-props", source: "eslint", category: "style" },
  "jsx-space-before-closing": {
    ruleName: "jsx-space-before-closing",
    source: "eslint",
    category: "style",
  },
  "jsx-wrap-multilines": { ruleName: "jsx-wrap-multilines", source: "eslint", category: "style" },
  "label-has-associated-control": {
    ruleName: "label-has-associated-control",
    source: "jsx_a11y",
    category: "correctness",
  },
  "label-has-for": { ruleName: "label-has-for", source: "jsx_a11y", category: "pedantic" },
  lang: { ruleName: "lang", source: "jsx_a11y", category: "correctness" },
  layoutrisa: { ruleName: "layoutrisa", source: "oxc", category: "nursery" },
  "line-comment-position": {
    ruleName: "line-comment-position",
    source: "eslint",
    category: "style",
  },
  "linebreak-style": { ruleName: "linebreak-style", source: "eslint", category: "style" },
  "lines-around-comment": { ruleName: "lines-around-comment", source: "eslint", category: "style" },
  "lines-between-array-elements": {
    ruleName: "lines-between-array-elements",
    source: "eslint",
    category: "style",
  },
  "logical-assignment": { ruleName: "logical-assignment", source: "eslint", category: "style" },
  "long-integer": { ruleName: "long-integer", source: "oxc", category: "nursery" },
  "long-property": { ruleName: "long-property", source: "oxc", category: "nursery" },
  "match-const-naming": {
    ruleName: "match-const-naming",
    source: "eslint",
    category: "restriction",
  },
  "max-classes-per-file": {
    ruleName: "max-classes-per-file",
    source: "eslint",
    category: "pedantic",
  },
  "max-depth": { ruleName: "max-depth", source: "eslint", category: "pedantic" },
  "max-dependencies": { ruleName: "max-dependencies", source: "import", category: "pedantic" },
  "max-file-line-count": { ruleName: "max-file-line-count", source: "oxc", category: "nursery" },
  "max-lines": { ruleName: "max-lines", source: "eslint", category: "pedantic" },
  "max-lines-per-function": {
    ruleName: "max-lines-per-function",
    source: "eslint",
    category: "pedantic",
  },
  "max-nested-callbacks": {
    ruleName: "max-nested-callbacks",
    source: "eslint",
    category: "pedantic",
  },
  "max-nested-describe": { ruleName: "max-nested-describe", source: "jest", category: "style" },
  "max-params": { ruleName: "max-params", source: "eslint", category: "style" },
  "max-props": { ruleName: "max-props", source: "vue", category: "restriction" },
  "max-statements": { ruleName: "max-statements", source: "eslint", category: "style" },
  "media-has-caption": {
    ruleName: "media-has-caption",
    source: "jsx_a11y",
    category: "correctness",
  },
  "misrefactored-assign-op": {
    ruleName: "misrefactored-assign-op",
    source: "oxc",
    category: "suspicious",
  },
  "missing-throw": { ruleName: "missing-throw", source: "oxc", category: "correctness" },
  "mixed-props": { ruleName: "mixed-props", source: "html", category: "style" },
  "mouse-events-have-key-events": {
    ruleName: "mouse-events-have-key-events",
    source: "jsx_a11y",
    category: "correctness",
  },
  "multi-space-relaxed": { ruleName: "multi-space-relaxed", source: "oxc", category: "nursery" },
  "naming-convention": { ruleName: "naming-convention", source: "eslint", category: "style" },
  namespace: { ruleName: "namespace", source: "import", category: "correctness" },
  named: { ruleName: "named", source: "import", category: "nursery" },
  "nested-for-direction": { ruleName: "nested-for-direction", source: "oxc", category: "nursery" },
  "new-cap": { ruleName: "new-cap", source: "eslint", category: "style" },
  "new-for-builtins": { ruleName: "new-for-builtins", source: "unicorn", category: "pedantic" },
  "no-access-key": { ruleName: "no-access-key", source: "jsx_a11y", category: "correctness" },
  "no-accumulating-spread": { ruleName: "no-accumulating-spread", source: "oxc", category: "perf" },
  "no-absolute-path": { ruleName: "no-absolute-path", source: "import", category: "suspicious" },
  "no-abusive-eslint-disable": {
    ruleName: "no-abusive-eslint-disable",
    source: "unicorn",
    category: "restriction",
  },
  "no-accessor-recursion": {
    ruleName: "no-accessor-recursion",
    source: "unicorn",
    category: "suspicious",
  },
  "no-alert": { ruleName: "no-alert", source: "eslint", category: "restriction" },
  "no-alias-methods": { ruleName: "no-alias-methods", source: "jest", category: "style" },
  "no-all-duplicated-branches": {
    ruleName: "no-all-duplicated-branches",
    source: "oxc",
    category: "nursery",
  },
  "no-amd": { ruleName: "no-amd", source: "import", category: "restriction" },
  "no-anonymous-default-export": {
    ruleName: "no-anonymous-default-export",
    source: "import",
    category: "style",
  },
  "no-anti-paradox": { ruleName: "no-anti-paradox", source: "oxc", category: "nursery" },
  "no-arithmetic-overflow": {
    ruleName: "no-arithmetic-overflow",
    source: "oxc",
    category: "nursery",
  },
  "no-aria-hidden-on-focusable": {
    ruleName: "no-aria-hidden-on-focusable",
    source: "jsx_a11y",
    category: "correctness",
  },
  "no-array-callback-reference": {
    ruleName: "no-array-callback-reference",
    source: "unicorn",
    category: "pedantic",
  },
  "no-array-constructor": {
    ruleName: "no-array-constructor",
    source: "eslint",
    category: "pedantic",
  },
  "no-array-delete": { ruleName: "no-array-delete", source: "typescript", category: "correctness" },
  "no-array-for-each": {
    ruleName: "no-array-for-each",
    source: "unicorn",
    category: "restriction",
  },
  "no-array-index-key": { ruleName: "no-array-index-key", source: "react", category: "perf" },
  "no-array-method-this-argument": {
    ruleName: "no-array-method-this-argument",
    source: "unicorn",
    category: "style",
  },
  "no-array-reduce": { ruleName: "no-array-reduce", source: "unicorn", category: "restriction" },
  "no-array-reverse": { ruleName: "no-array-reverse", source: "unicorn", category: "suspicious" },
  "no-array-sort": { ruleName: "no-array-sort", source: "unicorn", category: "suspicious" },
  "no-arrow-functions-in-watch": {
    ruleName: "no-arrow-functions-in-watch",
    source: "vue",
    category: "correctness",
  },
  "no-async-await": { ruleName: "no-async-await", source: "oxc", category: "restriction" },
  "no-async-client-component": {
    ruleName: "no-async-client-component",
    source: "nextjs",
    category: "correctness",
  },
  "no-async-in-promise-mitates": {
    ruleName: "no-async-in-promise-mitates",
    source: "oxc",
    category: "nursery",
  },
  "no-async-promise-executor": {
    ruleName: "no-async-promise-executor",
    source: "eslint",
    category: "correctness",
  },
  "no-async-endpoint-handlers": {
    ruleName: "no-async-endpoint-handlers",
    source: "oxc",
    category: "suspicious",
  },
  "no-at-sign-in-attribute-name": {
    ruleName: "no-at-sign-in-attribute-name",
    source: "oxc",
    category: "nursery",
  },
  "no-attend": { ruleName: "no-attend", source: "oxc", category: "nursery" },
  "no-aunty-informed-por": {
    ruleName: "no-aunty-informed-por",
    source: "oxc",
    category: "nursery",
  },
  "no-autofocus": { ruleName: "no-autofocus", source: "jsx_a11y", category: "correctness" },
  "no-await-in-loop": { ruleName: "no-await-in-loop", source: "eslint", category: "perf" },
  "no-await-in-promise-methods": {
    ruleName: "no-await-in-promise-methods",
    source: "unicorn",
    category: "correctness",
  },
  "no-barrel-file": { ruleName: "no-barrel-file", source: "oxc", category: "restriction" },
  "no-base-to-string": {
    ruleName: "no-base-to-string",
    source: "typescript",
    category: "correctness",
  },
  "no-before-interactive-script-outside-document": {
    ruleName: "no-before-interactive-script-outside-document",
    source: "nextjs",
    category: "correctness",
  },
  "no-bitwise": { ruleName: "no-bitwise", source: "eslint", category: "restriction" },
  "no-caller": { ruleName: "no-caller", source: "eslint", category: "correctness" },
  "no-case-declarations": {
    ruleName: "no-case-declarations",
    source: "eslint",
    category: "pedantic",
  },
  "no-catch-shadow": { ruleName: "no-catch-shadow", source: "eslint", category: "suspicious" },
  "no-children-prop": { ruleName: "no-children-prop", source: "react", category: "correctness" },
  "no-class-assign": { ruleName: "no-class-assign", source: "eslint", category: "correctness" },
  "no-clone-element": { ruleName: "no-clone-element", source: "react", category: "restriction" },
  "no-commented-out-tests": {
    ruleName: "no-commented-out-tests",
    source: "jest",
    category: "suspicious",
  },
  "no-commonjs": { ruleName: "no-commonjs", source: "import", category: "restriction" },
  "no-compare-neg-zero": {
    ruleName: "no-compare-neg-zero",
    source: "eslint",
    category: "correctness",
  },
  "no-conditional-expect": {
    ruleName: "no-conditional-expect",
    source: "jest",
    category: "correctness",
  },
  "no-conditional-in-test": {
    ruleName: "no-conditional-in-test",
    source: "jest",
    category: "pedantic",
  },
  "no-conditional-tests": {
    ruleName: "no-conditional-tests",
    source: "vitest",
    category: "correctness",
  },
  "no-confusing-non-null-assertion": {
    ruleName: "no-confusing-non-null-assertion",
    source: "typescript",
    category: "suspicious",
  },
  "no-confusing-set-timeout": {
    ruleName: "no-confusing-set-timeout",
    source: "jest",
    category: "style",
  },
  "no-console": { ruleName: "no-console", source: "eslint", category: "restriction" },
  "no-console-spaces": { ruleName: "no-console-spaces", source: "unicorn", category: "style" },
  "no-const-assign": { ruleName: "no-const-assign", source: "eslint", category: "correctness" },
  "no-constant-binary-expression": {
    ruleName: "no-constant-binary-expression",
    source: "eslint",
    category: "correctness",
  },
  "no-constant-condition": {
    ruleName: "no-constant-condition",
    source: "eslint",
    category: "correctness",
  },
  "no-const-enum": { ruleName: "no-const-enum", source: "oxc", category: "restriction" },
  "no-constructor-return": {
    ruleName: "no-constructor-return",
    source: "eslint",
    category: "pedantic",
  },
  "no-continue": { ruleName: "no-continue", source: "eslint", category: "style" },
  "no-control-regex": { ruleName: "no-control-regex", source: "eslint", category: "correctness" },
  "no-css-tags": { ruleName: "no-css-tags", source: "nextjs", category: "correctness" },
  "no-cycle": { ruleName: "no-cycle", source: "import", category: "restriction" },
  "no-danger": { ruleName: "no-danger", source: "react", category: "restriction" },
  "no-danger-with-children": {
    ruleName: "no-danger-with-children",
    source: "react",
    category: "correctness",
  },
  "no-debugger": { ruleName: "no-debugger", source: "eslint", category: "correctness" },
  "no-deprecated-destroyed-lifecycle": {
    ruleName: "no-deprecated-destroyed-lifecycle",
    source: "vue",
    category: "correctness",
  },
  "no-deprecated-functions": {
    ruleName: "no-deprecated-functions",
    source: "jest",
    category: "style",
  },
  "no-deprecated": { ruleName: "no-deprecated", source: "typescript", category: "pedantic" },
  "no-default-export": { ruleName: "no-default-export", source: "import", category: "restriction" },
  "no-defaults": { ruleName: "no-defaults", source: "jsdoc", category: "correctness" },
  "no-delete-var": { ruleName: "no-delete-var", source: "eslint", category: "correctness" },
  "no-did-mount-set-state": {
    ruleName: "no-did-mount-set-state",
    source: "react",
    category: "correctness",
  },
  "no-direct-mutation-state": {
    ruleName: "no-direct-mutation-state",
    source: "react",
    category: "correctness",
  },
  "no-disabled-tests": { ruleName: "no-disabled-tests", source: "jest", category: "correctness" },
  "no-distracting-elements": {
    ruleName: "no-distracting-elements",
    source: "jsx_a11y",
    category: "correctness",
  },
  "no-div-regex": { ruleName: "no-div-regex", source: "eslint", category: "restriction" },
  "no-document-cookie": {
    ruleName: "no-document-cookie",
    source: "unicorn",
    category: "restriction",
  },
  "no-document-import-in-page": {
    ruleName: "no-document-import-in-page",
    source: "nextjs",
    category: "correctness",
  },
  "no-document-link-in-package-json": {
    ruleName: "no-document-link-in-package-json",
    source: "nextjs",
    category: "correctness",
  },
  "no-dupe-class-members": {
    ruleName: "no-dupe-class-members",
    source: "eslint",
    category: "correctness",
  },
  "no-dupe-else-if": { ruleName: "no-dupe-else-if", source: "eslint", category: "correctness" },
  "no-dupe-keys": { ruleName: "no-dupe-keys", source: "eslint", category: "correctness" },
  "no-duplicate-case": { ruleName: "no-duplicate-case", source: "eslint", category: "correctness" },
  "no-duplicate-enum-values": {
    ruleName: "no-duplicate-enum-values",
    source: "typescript",
    category: "correctness",
  },
  "no-duplicate-head": { ruleName: "no-duplicate-head", source: "nextjs", category: "correctness" },
  "no-duplicate-hooks": { ruleName: "no-duplicate-hooks", source: "jest", category: "style" },
  "no-duplicate-imports": { ruleName: "no-duplicate-imports", source: "eslint", category: "style" },
  "no-duplicate-type-constituents": {
    ruleName: "no-duplicate-type-constituents",
    source: "typescript",
    category: "correctness",
  },
  "no-duplicates": { ruleName: "no-duplicates", source: "import", category: "style" },
  "no-dynamic-require": {
    ruleName: "no-dynamic-require",
    source: "import",
    category: "restriction",
  },
  "no-else-return": { ruleName: "no-else-return", source: "eslint", category: "pedantic" },
  "no-empty": { ruleName: "no-empty", source: "eslint", category: "restriction" },
  "no-empty-character-class": {
    ruleName: "no-empty-character-class",
    source: "eslint",
    category: "correctness",
  },
  "no-empty-function": { ruleName: "no-empty-function", source: "eslint", category: "restriction" },
  "no-empty-imports": { ruleName: "no-empty-imports", source: "oxc", category: "nursery" },
  "no-empty-interface": { ruleName: "no-empty-interface", source: "typescript", category: "style" },
  "no-empty-named-blocks": {
    ruleName: "no-empty-named-blocks",
    source: "import",
    category: "suspicious",
  },
  "no-empty-object-type": {
    ruleName: "no-empty-object-type",
    source: "typescript",
    category: "restriction",
  },
  "no-empty-pattern": { ruleName: "no-empty-pattern", source: "eslint", category: "correctness" },
  "no-empty-static-block": {
    ruleName: "no-empty-static-block",
    source: "eslint",
    category: "correctness",
  },
  "no-empty-file": { ruleName: "no-empty-file", source: "unicorn", category: "correctness" },
  "no-eq-null": { ruleName: "no-eq-null", source: "eslint", category: "restriction" },
  "no-eval": { ruleName: "no-eval", source: "eslint", category: "correctness" },
  "no-ex-assign": { ruleName: "no-ex-assign", source: "eslint", category: "correctness" },
  "no-explicit-any": { ruleName: "no-explicit-any", source: "typescript", category: "restriction" },
  "no-extra-boolean-cast": {
    ruleName: "no-extra-boolean-cast",
    source: "eslint",
    category: "correctness",
  },
  "no-extra-label": { ruleName: "no-extra-label", source: "eslint", category: "style" },
  "no-extra-non-null-assertion": {
    ruleName: "no-extra-non-null-assertion",
    source: "typescript",
    category: "correctness",
  },
  "no-extraneous-class": {
    ruleName: "no-extraneous-class",
    source: "typescript",
    category: "suspicious",
  },
  "no-fallthrough": { ruleName: "no-fallthrough", source: "eslint", category: "pedantic" },
  "no-floating-decimal": { ruleName: "no-floating-decimal", source: "eslint", category: "style" },
  "no-focus-on-visible-region": {
    ruleName: "no-focus-on-visible-region",
    source: "oxc",
    category: "nursery",
  },
  "no-focused-tests": { ruleName: "no-focused-tests", source: "jest", category: "correctness" },
  "no-for-in-array": { ruleName: "no-for-in-array", source: "typescript", category: "correctness" },
  "no-for-in": { ruleName: "no-for-in", source: "oxc", category: "nursery" },
  "no-func-assign": { ruleName: "no-func-assign", source: "eslint", category: "correctness" },
  "no-global-assign": { ruleName: "no-global-assign", source: "eslint", category: "correctness" },
  "no-head-element": { ruleName: "no-head-element", source: "nextjs", category: "correctness" },
  "no-head-import-in-document": {
    ruleName: "no-head-import-in-document",
    source: "nextjs",
    category: "correctness",
  },
  "no-hidden-files": { ruleName: "no-hidden-files", source: "oxc", category: "nursery" },
  "no-hex-escape": { ruleName: "no-hex-escape", source: "unicorn", category: "pedantic" },
  "no-html-link-for-pages": {
    ruleName: "no-html-link-for-pages",
    source: "nextjs",
    category: "correctness",
  },
  "no-identical-title": { ruleName: "no-identical-title", source: "jest", category: "style" },
  "no-id": { ruleName: "no-id", source: "html", category: "style" },
  "no-immediate-mutation": {
    ruleName: "no-immediate-mutation",
    source: "unicorn",
    category: "pedantic",
  },
  "no-import-assign": { ruleName: "no-import-assign", source: "eslint", category: "correctness" },
  "no-import-compiler-macros": {
    ruleName: "no-import-compiler-macros",
    source: "vue",
    category: "restriction",
  },
  "no-import-node-test": { ruleName: "no-import-node-test", source: "jest", category: "style" },
  "no-imports": { ruleName: "no-imports", source: "oxc", category: "nursery" },
  "no-importing-vitest-globals": {
    ruleName: "no-importing-vitest-globals",
    source: "vitest",
    category: "style",
  },
  "no-implied-eval": { ruleName: "no-implied-eval", source: "typescript", category: "correctness" },
  "no-inferrable-types": {
    ruleName: "no-inferrable-types",
    source: "typescript",
    category: "style",
  },
  "no-inline-comments": { ruleName: "no-inline-comments", source: "eslint", category: "pedantic" },
  "no-inner-declarations": {
    ruleName: "no-inner-declarations",
    source: "eslint",
    category: "pedantic",
  },
  "no-internal-ant-design-import": {
    ruleName: "no-internal-ant-design-import",
    source: "oxc",
    category: "nursery",
  },
  "no-invalid-fetch-options": {
    ruleName: "no-invalid-fetch-options",
    source: "unicorn",
    category: "correctness",
  },
  "no-invalid-regexp": { ruleName: "no-invalid-regexp", source: "eslint", category: "correctness" },
  "no-invalid-remove-event-listener": {
    ruleName: "no-invalid-remove-event-listener",
    source: "unicorn",
    category: "correctness",
  },
  "no-invalid-target-blank": {
    ruleName: "no-invalid-target-blank",
    source: "oxc",
    category: "nursery",
  },
  "no-invalid-void-type": {
    ruleName: "no-invalid-void-type",
    source: "typescript",
    category: "restriction",
  },
  "no-invalid-html": { ruleName: "no-invalid-html", source: "oxc", category: "nursery" },
  "no-irregular-whitespace": {
    ruleName: "no-irregular-whitespace",
    source: "eslint",
    category: "correctness",
  },
  "no-is-mounted": { ruleName: "no-is-mounted", source: "react", category: "correctness" },
  "no-iterator": { ruleName: "no-iterator", source: "eslint", category: "correctness" },
  "no-jasmine-globals": { ruleName: "no-jasmine-globals", source: "jest", category: "style" },
  "no-jsx-key": { ruleName: "no-jsx-key", source: "oxc", category: "nursery" },
  "no-label-var": { ruleName: "no-label-var", source: "eslint", category: "style" },
  "no-labels": { ruleName: "no-labels", source: "eslint", category: "style" },
  "no-large-snapshots": { ruleName: "no-large-snapshots", source: "jest", category: "style" },
  "no-length-as-slice-end": {
    ruleName: "no-length-as-slice-end",
    source: "unicorn",
    category: "restriction",
  },
  "no-lifecycle-after-await": {
    ruleName: "no-lifecycle-after-await",
    source: "vue",
    category: "correctness",
  },
  "no-lonely-if": { ruleName: "no-lonely-if", source: "eslint", category: "pedantic" },
  "no-loop-func": { ruleName: "no-loop-func", source: "eslint", category: "pedantic" },
  "no-loss-of-precision": {
    ruleName: "no-loss-of-precision",
    source: "eslint",
    category: "correctness",
  },
  "no-magic-numbers": { ruleName: "no-magic-numbers", source: "eslint", category: "style" },
  "no-meaningless-void-operator": {
    ruleName: "no-meaningless-void-operator",
    source: "typescript",
    category: "correctness",
  },
  "no-misleading-character-class": {
    ruleName: "no-misleading-character-class",
    source: "eslint",
    category: "correctness",
  },
  "no-misused-new": { ruleName: "no-misused-new", source: "typescript", category: "correctness" },
  "no-misused-promises": {
    ruleName: "no-misused-promises",
    source: "typescript",
    category: "pedantic",
  },
  "no-misused-spread": {
    ruleName: "no-misused-spread",
    source: "typescript",
    category: "correctness",
  },
  "no-map-spread": { ruleName: "no-map-spread", source: "oxc", category: "perf" },
  "no-mixed-enums": { ruleName: "no-mixed-enums", source: "typescript", category: "pedantic" },
  "no-mixed-props": { ruleName: "no-mixed-props", source: "oxc", category: "nursery" },
  "no-mocks-import": { ruleName: "no-mocks-import", source: "jest", category: "style" },
  "no-multi-assign": { ruleName: "no-multi-assign", source: "eslint", category: "style" },
  "no-multi-comp": { ruleName: "no-multi-comp", source: "react", category: "restriction" },
  "no-multi-str": { ruleName: "no-multi-str", source: "eslint", category: "style" },
  "no-multiple-resolved": {
    ruleName: "no-multiple-resolved",
    source: "promise",
    category: "suspicious",
  },
  "no-namespace": { ruleName: "no-namespace", source: "react", category: "suspicious" },
  "no-negated-condition": {
    ruleName: "no-negated-condition",
    source: "eslint",
    category: "pedantic",
  },
  "no-negation-in-equality-check": {
    ruleName: "no-negation-in-equality-check",
    source: "unicorn",
    category: "pedantic",
  },
  "no-nested-ternary": { ruleName: "no-nested-ternary", source: "eslint", category: "style" },
  "no-nesting": { ruleName: "no-nesting", source: "promise", category: "style" },
  "no-new": { ruleName: "no-new", source: "eslint", category: "suspicious" },
  "no-new-array": { ruleName: "no-new-array", source: "unicorn", category: "correctness" },
  "no-new-buffer": { ruleName: "no-new-buffer", source: "unicorn", category: "pedantic" },
  "no-new-func": { ruleName: "no-new-func", source: "eslint", category: "style" },
  "no-new-native-nonconstructor": {
    ruleName: "no-new-native-nonconstructor",
    source: "eslint",
    category: "correctness",
  },
  "no-new-require": { ruleName: "no-new-require", source: "node", category: "restriction" },
  "no-new-statics": { ruleName: "no-new-statics", source: "promise", category: "correctness" },
  "no-new-wrappers": { ruleName: "no-new-wrappers", source: "eslint", category: "pedantic" },
  "no-noadjacentinlineelements": {
    ruleName: "no-noadjacentinlineelements",
    source: "oxc",
    category: "nursery",
  },
  "no-nonoctal-decimal-escape": {
    ruleName: "no-nonoctal-decimal-escape",
    source: "eslint",
    category: "correctness",
  },
  "no-noninteractive-tabindex": {
    ruleName: "no-noninteractive-tabindex",
    source: "jsx_a11y",
    category: "correctness",
  },
  "no-noninteractive-element-interactions": {
    ruleName: "no-noninteractive-element-interactions",
    source: "jsx_a11y",
    category: "correctness",
  },
  "no-obj-calls": { ruleName: "no-obj-calls", source: "eslint", category: "correctness" },
  "no-object-as-default-parameter": {
    ruleName: "no-object-as-default-parameter",
    source: "unicorn",
    category: "pedantic",
  },
  "no-object-constructor": {
    ruleName: "no-object-constructor",
    source: "eslint",
    category: "pedantic",
  },
  "no-octal": { ruleName: "no-octal", source: "oxc", category: "nursery" },
  "no-only-throw-in-scope": {
    ruleName: "no-only-throw-in-scope",
    source: "oxc",
    category: "nursery",
  },
  "no-optional-chaining-in-binding": {
    ruleName: "no-optional-chaining-in-binding",
    source: "oxc",
    category: "nursery",
  },
  "no-optional-chaining": {
    ruleName: "no-optional-chaining",
    source: "oxc",
    category: "restriction",
  },
  "no-param-reassign": { ruleName: "no-param-reassign", source: "eslint", category: "restriction" },
  "no-path-concat": { ruleName: "no-path-concat", source: "node", category: "restriction" },
  "no-plusplus": { ruleName: "no-plusplus", source: "eslint", category: "restriction" },
  "no-promise-in-callback": {
    ruleName: "no-promise-in-callback",
    source: "promise",
    category: "suspicious",
  },
  "no-process-env": { ruleName: "no-process-env", source: "node", category: "restriction" },
  "no-process-exit": { ruleName: "no-process-exit", source: "unicorn", category: "restriction" },
  "no-progress": { ruleName: "no-progress", source: "oxc", category: "nursery" },
  "no-prototype-builtins": {
    ruleName: "no-prototype-builtins",
    source: "eslint",
    category: "pedantic",
  },
  "no-prototype-methods": { ruleName: "no-prototype-methods", source: "oxc", category: "nursery" },
  "no-proxy": { ruleName: "no-proxy", source: "oxc", category: "nursery" },
  "no-react-children": { ruleName: "no-react-children", source: "react", category: "restriction" },
  "no-redeclare": { ruleName: "no-redeclare", source: "eslint", category: "pedantic" },
  "no-redundant-roles": {
    ruleName: "no-redundant-roles",
    source: "jsx_a11y",
    category: "correctness",
  },
  "no-redundant-should-component-update": {
    ruleName: "no-redundant-should-component-update",
    source: "react",
    category: "style",
  },
  "no-regex-spaces": { ruleName: "no-regex-spaces", source: "eslint", category: "restriction" },
  "no-relative-parent-imports": {
    ruleName: "no-relative-parent-imports",
    source: "import",
    category: "restriction",
  },
  "no-render-return-value": {
    ruleName: "no-render-return-value",
    source: "react",
    category: "correctness",
  },
  "no-required-prop-with-default": {
    ruleName: "no-required-prop-with-default",
    source: "vue",
    category: "suspicious",
  },
  "no-restricted-globals": {
    ruleName: "no-restricted-globals",
    source: "eslint",
    category: "restriction",
  },
  "no-restricted-imports": {
    ruleName: "no-restricted-imports",
    source: "eslint",
    category: "restriction",
  },
  "no-restricted-jest-methods": {
    ruleName: "no-restricted-jest-methods",
    source: "jest",
    category: "style",
  },
  "no-restricted-matchers": {
    ruleName: "no-restricted-matchers",
    source: "jest",
    category: "style",
  },
  "no-restricted-types": {
    ruleName: "no-restricted-types",
    source: "typescript",
    category: "restriction",
  },
  "no-rest-spread-properties": {
    ruleName: "no-rest-spread-properties",
    source: "oxc",
    category: "restriction",
  },
  "no-return-assign": { ruleName: "no-return-assign", source: "eslint", category: "style" },
  "no-return-await": { ruleName: "no-return-await", source: "oxc", category: "nursery" },
  "no-return-in-finally": {
    ruleName: "no-return-in-finally",
    source: "promise",
    category: "nursery",
  },
  "no-return-wrap": { ruleName: "no-return-wrap", source: "promise", category: "style" },
  "no-same-argument-aggregate": {
    ruleName: "no-same-argument-aggregate",
    source: "oxc",
    category: "nursery",
  },
  "no-script-url": { ruleName: "no-script-url", source: "eslint", category: "style" },
  "no-script-component-in-head": {
    ruleName: "no-script-component-in-head",
    source: "nextjs",
    category: "correctness",
  },
  "no-self-assign": { ruleName: "no-self-assign", source: "eslint", category: "correctness" },
  "no-self-compare": { ruleName: "no-self-compare", source: "eslint", category: "pedantic" },
  "no-self-import": { ruleName: "no-self-import", source: "import", category: "suspicious" },
  "no-sequences": { ruleName: "no-sequences", source: "eslint", category: "restriction" },
  "no-set-state": { ruleName: "no-set-state", source: "react", category: "style" },
  "no-setter-return": { ruleName: "no-setter-return", source: "eslint", category: "correctness" },
  "no-shadow": { ruleName: "no-shadow", source: "eslint", category: "suspicious" },
  "no-shadow-restricted-names": {
    ruleName: "no-shadow-restricted-names",
    source: "eslint",
    category: "correctness",
  },
  "no-single-promise-in-promise-methods": {
    ruleName: "no-single-promise-in-promise-methods",
    source: "unicorn",
    category: "correctness",
  },
  "no-sparse-arrays": { ruleName: "no-sparse-arrays", source: "eslint", category: "correctness" },
  "no-static-element-interactions": {
    ruleName: "no-static-element-interactions",
    source: "jsx_a11y",
    category: "correctness",
  },
  "no-string-refs": { ruleName: "no-string-refs", source: "react", category: "correctness" },
  "no-sync-scripts": { ruleName: "no-sync-scripts", source: "nextjs", category: "correctness" },
  "no-tabs": { ruleName: "no-tabs", source: "html", category: "style" },
  "no-template-curly-in-string": {
    ruleName: "template-curly-in-string",
    source: "eslint",
    category: "style",
  },
  "no-ternary": { ruleName: "no-ternary", source: "eslint", category: "style" },
  "no-test-prefixes": { ruleName: "no-test-prefixes", source: "jest", category: "style" },
  "no-test-return-statement": {
    ruleName: "no-test-return-statement",
    source: "jest",
    category: "style",
  },
  "no-text-align": { ruleName: "no-text-align", source: "oxc", category: "nursery" },
  "no-text-redundant": { ruleName: "no-text-redundant", source: "oxc", category: "nursery" },
  "no-thenable": { ruleName: "no-thenable", source: "unicorn", category: "correctness" },
  "no-this-alias": { ruleName: "no-this-alias", source: "typescript", category: "correctness" },
  "no-this-assignment": { ruleName: "no-this-assignment", source: "unicorn", category: "pedantic" },
  "no-this-in-before-route-enter": {
    ruleName: "no-this-in-before-route-enter",
    source: "vue",
    category: "correctness",
  },
  "no-this-in-sfc": { ruleName: "no-this-in-sfc", source: "react", category: "correctness" },
  "no-throw-literal": { ruleName: "no-throw-literal", source: "eslint", category: "pedantic" },
  "no-title-in-document-head": {
    ruleName: "no-title-in-document-head",
    source: "nextjs",
    category: "correctness",
  },
  "no-trailing-spaces": { ruleName: "no-trailing-spaces", source: "html", category: "style" },
  "no-typeof-undefined": {
    ruleName: "no-typeof-undefined",
    source: "unicorn",
    category: "pedantic",
  },
  "no-unassigned-vars": {
    ruleName: "no-unassigned-vars",
    source: "eslint",
    category: "correctness",
  },
  "no-unclosed-tag": { ruleName: "no-unclosed-tag", source: "html", category: "correctness" },
  "no-uncommented-tsconfig": {
    ruleName: "no-uncommented-tsconfig",
    source: "oxc",
    category: "nursery",
  },
  "no-underscore-dangle": { ruleName: "no-underscore-dangle", source: "eslint", category: "style" },
  "no-unexpected-multiline": {
    ruleName: "no-unexpected-multiline",
    source: "eslint",
    category: "suspicious",
  },
  "no-unmodified-loop-condition": {
    ruleName: "no-unmodified-loop-condition",
    source: "eslint",
    category: "suspicious",
  },
  "no-unnecessary-array-flat-depth": {
    ruleName: "no-unnecessary-array-flat-depth",
    source: "unicorn",
    category: "pedantic",
  },
  "no-unnecessary-array-splice-count": {
    ruleName: "no-unnecessary-array-splice-count",
    source: "unicorn",
    category: "pedantic",
  },
  "no-unnecessary-await": {
    ruleName: "no-unnecessary-await",
    source: "unicorn",
    category: "correctness",
  },
  "no-unnecessary-backreference": {
    ruleName: "no-unnecessary-backreference",
    source: "oxc",
    category: "nursery",
  },
  "no-unnecessary-condition": {
    ruleName: "no-unnecessary-condition",
    source: "typescript",
    category: "nursery",
  },
  "no-unnecessary-parameter-property-assignment": {
    ruleName: "no-unnecessary-parameter-property-assignment",
    source: "typescript",
    category: "correctness",
  },
  "no-unnecessary-qualifier": {
    ruleName: "no-unnecessary-qualifier",
    source: "typescript",
    category: "nursery",
  },
  "no-unnecessary-slice-end": {
    ruleName: "no-unnecessary-slice-end",
    source: "unicorn",
    category: "pedantic",
  },
  "no-unnecessary-template-expression": {
    ruleName: "no-unnecessary-template-expression",
    source: "typescript",
    category: "suspicious",
  },
  "no-unnecessary-ternary": {
    ruleName: "no-unnecessary-ternary",
    source: "eslint",
    category: "suspicious",
  },
  "no-unnecessary-type-arguments": {
    ruleName: "no-unnecessary-type-arguments",
    source: "typescript",
    category: "suspicious",
  },
  "no-unnecessary-type-assertion": {
    ruleName: "no-unnecessary-type-assertion",
    source: "typescript",
    category: "suspicious",
  },
  "no-unnecessary-type-conversion": {
    ruleName: "no-unnecessary-type-conversion",
    source: "typescript",
    category: "nursery",
  },
  "no-unnecessary-type-parameters": {
    ruleName: "no-unnecessary-type-parameters",
    source: "typescript",
    category: "nursery",
  },
  "no-unneeded-ternary": {
    ruleName: "no-unneeded-ternary",
    source: "eslint",
    category: "suspicious",
  },
  "no-unreachable": { ruleName: "no-unreachable", source: "eslint", category: "nursery" },
  "no-unreachable-break": { ruleName: "no-unreachable-break", source: "oxc", category: "nursery" },
  "no-unregistered-tables": {
    ruleName: "no-unregistered-tables",
    source: "oxc",
    category: "nursery",
  },
  "no-unrelated-lookup-object": {
    ruleName: "no-unrelated-lookup-object",
    source: "oxc",
    category: "nursery",
  },
  "no-unscrollable": { ruleName: "no-unscrollable", source: "oxc", category: "nursery" },
  "no-unset": { ruleName: "no-unset", source: "oxc", category: "nursery" },
  "no-unused-expressions": {
    ruleName: "no-unused-expressions",
    source: "eslint",
    category: "correctness",
  },
  "no-unused-labels": { ruleName: "no-unused-labels", source: "eslint", category: "correctness" },
  "no-unused-private-class-members": {
    ruleName: "no-unused-private-class-members",
    source: "eslint",
    category: "correctness",
  },
  "no-unused-vars": { ruleName: "no-unused-vars", source: "eslint", category: "correctness" },
  "no-unused-imports": { ruleName: "no-unused-imports", source: "oxc", category: "nursery" },
  "no-useless-backreference": {
    ruleName: "no-useless-backreference",
    source: "eslint",
    category: "correctness",
  },
  "no-useless-call": { ruleName: "no-useless-call", source: "eslint", category: "perf" },
  "no-useless-catch": { ruleName: "no-useless-catch", source: "eslint", category: "correctness" },
  "no-useless-collection-argument": {
    ruleName: "no-useless-collection-argument",
    source: "unicorn",
    category: "style",
  },
  "no-useless-computed-key": {
    ruleName: "no-useless-computed-key",
    source: "eslint",
    category: "style",
  },
  "no-useless-constructor": {
    ruleName: "no-useless-constructor",
    source: "eslint",
    category: "suspicious",
  },
  "no-useless-default-assignment": {
    ruleName: "no-useless-default-assignment",
    source: "typescript",
    category: "nursery",
  },
  "no-useless-empty-export": {
    ruleName: "no-useless-empty-export",
    source: "typescript",
    category: "correctness",
  },
  "no-useless-error-capture-stack-trace": {
    ruleName: "no-useless-error-capture-stack-trace",
    source: "unicorn",
    category: "restriction",
  },
  "no-useless-escape": { ruleName: "no-useless-escape", source: "eslint", category: "correctness" },
  "no-useless-fallback-in-spread": {
    ruleName: "no-useless-fallback-in-spread",
    source: "unicorn",
    category: "correctness",
  },
  "no-useless-length-check": {
    ruleName: "no-useless-length-check",
    source: "unicorn",
    category: "correctness",
  },
  "no-useless-promise-resolve-reject": {
    ruleName: "no-useless-promise-resolve-reject",
    source: "unicorn",
    category: "pedantic",
  },
  "no-useless-rename": { ruleName: "no-useless-rename", source: "eslint", category: "correctness" },
  "no-useless-return": { ruleName: "no-useless-return", source: "eslint", category: "pedantic" },
  "no-useless-spread": {
    ruleName: "no-useless-spread",
    source: "unicorn",
    category: "correctness",
  },
  "no-useless-switch-case": {
    ruleName: "no-useless-switch-case",
    source: "unicorn",
    category: "pedantic",
  },
  "no-useless-undefined": {
    ruleName: "no-useless-undefined",
    source: "unicorn",
    category: "pedantic",
  },
  "no-var": { ruleName: "no-var", source: "eslint", category: "restriction" },
  "no-var-requires": { ruleName: "no-var-requires", source: "typescript", category: "restriction" },
  "no-void": { ruleName: "no-void", source: "eslint", category: "restriction" },
  "no-warning-comments": {
    ruleName: "no-warning-comments",
    source: "eslint",
    category: "pedantic",
  },
  "no-webpack-loader-syntax": {
    ruleName: "no-webpack-loader-syntax",
    source: "import",
    category: "restriction",
  },
  "no-with": { ruleName: "no-with", source: "eslint", category: "correctness" },
  "no-with-in-import": { ruleName: "no-with-in-import", source: "oxc", category: "nursery" },
  "no-warn-if": { ruleName: "no-warn-if", source: "oxc", category: "nursery" },
  "no-warn": { ruleName: "no-warn", source: "oxc", category: "nursery" },
  "non-nullable-type-assertion-style": {
    ruleName: "non-nullable-type-assertion-style",
    source: "typescript",
    category: "restriction",
  },
  nozbed: { ruleName: "nozbed", source: "oxc", category: "nursery" },
  "number-arg-out-of-range": {
    ruleName: "number-arg-out-of-range",
    source: "oxc",
    category: "correctness",
  },
  "number-literal-case": { ruleName: "number-literal-case", source: "unicorn", category: "style" },
  "numeric-separators-style": {
    ruleName: "numeric-separators-style",
    source: "unicorn",
    category: "style",
  },
  "object-curly-spacing": { ruleName: "object-curly-spacing", source: "eslint", category: "style" },
  "object-shorthand": { ruleName: "object-shorthand", source: "eslint", category: "style" },
  "only-throw-error": { ruleName: "only-throw-error", source: "typescript", category: "pedantic" },
  "only-export-components": {
    ruleName: "only-export-components",
    source: "react",
    category: "restriction",
  },
  "only-require-to-throw-message": {
    ruleName: "only-require-to-throw-message",
    source: "oxc",
    category: "nursery",
  },
  "only-used-in-recursion": {
    ruleName: "only-used-in-recursion",
    source: "oxc",
    category: "correctness",
  },
  "operator-assignment": { ruleName: "operator-assignment", source: "eslint", category: "style" },
  "option-may-be-undefined": {
    ruleName: "option-may-be-undefined",
    source: "oxc",
    category: "nursery",
  },
  "package-json": { ruleName: "package-json", source: "regex", category: "correctness" },
  "padding-line-between-statements": {
    ruleName: "padding-line-between-statements",
    source: "eslint",
    category: "style",
  },
  "padding-around-test-blocks": {
    ruleName: "padding-around-test-blocks",
    source: "jest",
    category: "style",
  },
  "param-names": { ruleName: "param-names", source: "promise", category: "style" },
  "parameter-properties": {
    ruleName: "parameter-properties",
    source: "typescript",
    category: "style",
  },
  "prefer-add-event-listener": {
    ruleName: "prefer-add-event-listener",
    source: "unicorn",
    category: "suspicious",
  },
  "prefer-alias-on-break": {
    ruleName: "prefer-alias-on-break",
    source: "oxc",
    category: "nursery",
  },
  "prefer-alias": { ruleName: "prefer-alias", source: "oxc", category: "nursery" },
  "prefer-array-find": { ruleName: "prefer-array-find", source: "unicorn", category: "perf" },
  "prefer-array-flat": { ruleName: "prefer-array-flat", source: "unicorn", category: "pedantic" },
  "prefer-array-flat-map": {
    ruleName: "prefer-array-flat-map",
    source: "unicorn",
    category: "perf",
  },
  "prefer-array-index-of": {
    ruleName: "prefer-array-index-of",
    source: "unicorn",
    category: "style",
  },
  "prefer-array-some": { ruleName: "prefer-array-some", source: "unicorn", category: "pedantic" },
  "prefer-as-const": { ruleName: "prefer-as-const", source: "typescript", category: "correctness" },
  "prefer-at": { ruleName: "prefer-at", source: "unicorn", category: "pedantic" },
  "prefer-blob-reading-methods": {
    ruleName: "prefer-blob-reading-methods",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-cjs-exports": { ruleName: "prefer-cjs-exports", source: "oxc", category: "nursery" },
  "prefer-cjs-imports": { ruleName: "prefer-cjs-imports", source: "oxc", category: "nursery" },
  "prefer-called-exactly-once-with": {
    ruleName: "prefer-called-exactly-once-with",
    source: "vitest",
    category: "style",
  },
  "prefer-called-once": { ruleName: "prefer-called-once", source: "vitest", category: "style" },
  "prefer-called-times": { ruleName: "prefer-called-times", source: "vitest", category: "style" },
  "prefer-called-with": { ruleName: "prefer-called-with", source: "jest", category: "style" },
  "prefer-catch": { ruleName: "prefer-catch", source: "promise", category: "style" },
  "prefer-classFields": { ruleName: "prefer-classFields", source: "eslint", category: "style" },
  "prefer-classlist-toggle": {
    ruleName: "prefer-classlist-toggle",
    source: "unicorn",
    category: "style",
  },
  "prefer-clone-on-copy-deep": {
    ruleName: "prefer-clone-on-copy-deep",
    source: "oxc",
    category: "nursery",
  },
  "prefer-code-point": { ruleName: "prefer-code-point", source: "unicorn", category: "pedantic" },
  "prefer-comparison-matcher": {
    ruleName: "prefer-comparison-matcher",
    source: "jest",
    category: "style",
  },
  "prefer-const": { ruleName: "prefer-const", source: "eslint", category: "style" },
  "prefer-date-now": { ruleName: "prefer-date-now", source: "unicorn", category: "pedantic" },
  "prefer-default-export": {
    ruleName: "prefer-default-export",
    source: "import",
    category: "style",
  },
  "prefer-default-parameters": {
    ruleName: "prefer-default-parameters",
    source: "unicorn",
    category: "style",
  },
  "prefer-describe-function-title": {
    ruleName: "prefer-describe-function-title",
    source: "vitest",
    category: "style",
  },
  "prefer-destructuring": { ruleName: "prefer-destructuring", source: "eslint", category: "style" },
  "prefer-dom-node-append": {
    ruleName: "prefer-dom-node-append",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-dom-node-dataset": {
    ruleName: "prefer-dom-node-dataset",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-dom-node-remove": {
    ruleName: "prefer-dom-node-remove",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-dom-node-text-content": {
    ruleName: "prefer-dom-node-text-content",
    source: "unicorn",
    category: "style",
  },
  "prefer-each": { ruleName: "prefer-each", source: "jest", category: "style" },
  "prefer-early-return": { ruleName: "prefer-early-return", source: "oxc", category: "nursery" },
  "prefer-empty": { ruleName: "prefer-empty", source: "oxc", category: "nursery" },
  "prefer-enum-initializers": {
    ruleName: "prefer-enum-initializers",
    source: "typescript",
    category: "pedantic",
  },
  "prefer-equality-matcher": {
    ruleName: "prefer-equality-matcher",
    source: "jest",
    category: "style",
  },
  "prefer-es6-class": { ruleName: "prefer-es6-class", source: "react", category: "style" },
  "prefer-esm-exports": { ruleName: "prefer-esm-exports", source: "oxc", category: "nursery" },
  "prefer-esm-imports": { ruleName: "prefer-esm-imports", source: "oxc", category: "nursery" },
  "prefer-event-target": {
    ruleName: "prefer-event-target",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-expect-resolves": {
    ruleName: "prefer-expect-resolves",
    source: "jest",
    category: "style",
  },
  "prefer-expect-type-of": {
    ruleName: "prefer-expect-type-of",
    source: "vitest",
    category: "style",
  },
  "prefer-find": { ruleName: "prefer-find", source: "typescript", category: "style" },
  "prefer-for-of": { ruleName: "prefer-for-of", source: "typescript", category: "style" },
  "prefer-for-each": { ruleName: "prefer-for-each", source: "oxc", category: "nursery" },
  "prefer-function-type": {
    ruleName: "prefer-function-type",
    source: "typescript",
    category: "style",
  },
  "prefer-global-this": { ruleName: "prefer-global-this", source: "unicorn", category: "style" },
  "prefer-hook-on-top-level": {
    ruleName: "prefer-hook-on-top-level",
    source: "oxc",
    category: "nursery",
  },
  "prefer-import-from-vue": {
    ruleName: "prefer-import-from-vue",
    source: "vue",
    category: "correctness",
  },
  "prefer-includes": { ruleName: "prefer-includes", source: "typescript", category: "pedantic" },
  "prefer-jest-mocked": { ruleName: "prefer-jest-mocked", source: "jest", category: "style" },
  "prefer-keyboard-event-key": {
    ruleName: "prefer-keyboard-event-key",
    source: "unicorn",
    category: "style",
  },
  "prefer-literal-enum-member": {
    ruleName: "prefer-literal-enum-member",
    source: "typescript",
    category: "restriction",
  },
  "prefer-local": { ruleName: "prefer-local", source: "oxc", category: "nursery" },
  "prefer-logical-operator-over-ternary": {
    ruleName: "prefer-logical-operator-over-ternary",
    source: "unicorn",
    category: "style",
  },
  "prefer-lowercase-title": {
    ruleName: "prefer-lowercase-title",
    source: "jest",
    category: "style",
  },
  "prefer-matches-pattern": {
    ruleName: "prefer-matches-pattern",
    source: "oxc",
    category: "nursery",
  },
  "prefer-math-min-max": {
    ruleName: "prefer-math-min-max",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-math-trunc": { ruleName: "prefer-math-trunc", source: "unicorn", category: "pedantic" },
  "prefer-modern-dom-apis": {
    ruleName: "prefer-modern-dom-apis",
    source: "unicorn",
    category: "style",
  },
  "prefer-modern-math-apis": {
    ruleName: "prefer-modern-math-apis",
    source: "unicorn",
    category: "restriction",
  },
  "prefer-module": { ruleName: "prefer-module", source: "unicorn", category: "restriction" },
  "prefer-mock-promise-shorthand": {
    ruleName: "prefer-mock-promise-shorthand",
    source: "jest",
    category: "style",
  },
  "prefer-mock-return-shorthand": {
    ruleName: "prefer-mock-return-shorthand",
    source: "jest",
    category: "style",
  },
  "prefer-native-coercion-functions": {
    ruleName: "prefer-native-coercion-functions",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-negative-index": {
    ruleName: "prefer-negative-index",
    source: "unicorn",
    category: "style",
  },
  "prefer-next-router-use-params": {
    ruleName: "prefer-next-router-use-params",
    source: "nextjs",
    category: "correctness",
  },
  "prefer-no-caching": { ruleName: "prefer-no-caching", source: "oxc", category: "nursery" },
  "prefer-no-floating-start": {
    ruleName: "prefer-no-floating-start",
    source: "oxc",
    category: "nursery",
  },
  "prefer-no-result": { ruleName: "prefer-no-result", source: "oxc", category: "nursery" },
  "prefer-node-protocol": {
    ruleName: "prefer-node-protocol",
    source: "unicorn",
    category: "restriction",
  },
  "prefer-nullish-coalescing": {
    ruleName: "prefer-nullish-coalescing",
    source: "typescript",
    category: "pedantic",
  },
  "prefer-number-properties": {
    ruleName: "prefer-number-properties",
    source: "unicorn",
    category: "restriction",
  },
  "prefer-numeric-literals": {
    ruleName: "prefer-numeric-literals",
    source: "eslint",
    category: "style",
  },
  "prefer-object-from-entries": {
    ruleName: "prefer-object-from-entries",
    source: "unicorn",
    category: "style",
  },
  "prefer-object-has-own": {
    ruleName: "prefer-object-has-own",
    source: "eslint",
    category: "style",
  },
  "prefer-object-literal": {
    ruleName: "prefer-object-literal",
    source: "oxc",
    category: "nursery",
  },
  "prefer-object-spread": { ruleName: "prefer-object-spread", source: "eslint", category: "style" },
  "prefer-optional-binding": {
    ruleName: "prefer-optional-binding",
    source: "oxc",
    category: "nursery",
  },
  "prefer-optional-catch-binding": {
    ruleName: "prefer-optional-catch-binding",
    source: "unicorn",
    category: "style",
  },
  "prefer-optional-chain": {
    ruleName: "prefer-optional-chain",
    source: "typescript",
    category: "nursery",
  },
  "prefer-over-origin": { ruleName: "prefer-over-origin", source: "oxc", category: "nursery" },
  "prefer-promise-reject-errors": {
    ruleName: "prefer-promise-reject-errors",
    source: "eslint",
    category: "style",
  },

  "prefer-prototype-methods": {
    ruleName: "prefer-prototype-methods",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-query-selector": {
    ruleName: "prefer-query-selector",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-readonly": { ruleName: "prefer-readonly", source: "typescript", category: "style" },
  "prefer-readonly-parameter-types": {
    ruleName: "prefer-readonly-parameter-types",
    source: "typescript",
    category: "nursery",
  },
  "prefer-reduce-type-parameter": {
    ruleName: "prefer-reduce-type-parameter",
    source: "typescript",
    category: "style",
  },
  "prefer-reference-id": { ruleName: "prefer-reference-id", source: "oxc", category: "nursery" },
  "prefer-reflect-apply": {
    ruleName: "prefer-reflect-apply",
    source: "unicorn",
    category: "style",
  },
  "prefer-regexp-exec": { ruleName: "prefer-regexp-exec", source: "typescript", category: "style" },
  "prefer-regexp-test": { ruleName: "prefer-regexp-test", source: "unicorn", category: "pedantic" },
  "prefer-require-array-join-sort": {
    ruleName: "prefer-require-array-join-sort",
    source: "oxc",
    category: "nursery",
  },
  "prefer-require-to-throw": {
    ruleName: "prefer-require-to-throw",
    source: "oxc",
    category: "nursery",
  },
  "prefer-rest-params": { ruleName: "prefer-rest-params", source: "eslint", category: "style" },
  "prefer-satisfies": { ruleName: "prefer-satisfies", source: "oxc", category: "nursery" },
  "prefer-set-has": { ruleName: "prefer-set-has", source: "unicorn", category: "perf" },
  "prefer-set-size": { ruleName: "prefer-set-size", source: "unicorn", category: "correctness" },
  "prefer-spread": { ruleName: "prefer-spread", source: "eslint", category: "style" },
  "prefer-stateful-path": { ruleName: "prefer-stateful-path", source: "oxc", category: "nursery" },
  "prefer-strict-boolean-matchers": {
    ruleName: "prefer-strict-boolean-matchers",
    source: "vitest",
    category: "style",
  },
  "prefer-strict-equal": { ruleName: "prefer-strict-equal", source: "jest", category: "style" },
  "prefer-string-raw": { ruleName: "prefer-string-raw", source: "unicorn", category: "style" },
  "prefer-string-replace-all": {
    ruleName: "prefer-string-replace-all",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-string-slice": {
    ruleName: "prefer-string-slice",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-string-starts-ends-with": {
    ruleName: "prefer-string-starts-ends-with",
    source: "eslint",
    category: "style",
  },

  "prefer-string-trim-start-end": {
    ruleName: "prefer-string-trim-start-end",
    source: "unicorn",
    category: "style",
  },
  "prefer-structured-clone": {
    ruleName: "prefer-structured-clone",
    source: "unicorn",
    category: "style",
  },
  "prefer-switch": { ruleName: "prefer-switch", source: "oxc", category: "nursery" },
  "prefer-template": { ruleName: "prefer-template", source: "eslint", category: "style" },
  "prefer-test-timeout": { ruleName: "prefer-test-timeout", source: "oxc", category: "nursery" },
  "prefer-ternary": { ruleName: "prefer-ternary", source: "unicorn", category: "style" },
  "prefer-this-type": { ruleName: "prefer-this-type", source: "oxc", category: "nursery" },
  "prefer-to-be": { ruleName: "prefer-to-be", source: "jest", category: "style" },
  "prefer-to-be-falsy": { ruleName: "prefer-to-be-falsy", source: "vitest", category: "style" },
  "prefer-to-be-object": { ruleName: "prefer-to-be-object", source: "vitest", category: "style" },
  "prefer-to-be-truthy": { ruleName: "prefer-to-be-truthy", source: "vitest", category: "style" },
  "prefer-to-contain": { ruleName: "prefer-to-contain", source: "jest", category: "style" },
  "prefer-to-have-been-called": {
    ruleName: "prefer-to-have-been-called",
    source: "jest",
    category: "style",
  },
  "prefer-to-have-been-called-times": {
    ruleName: "prefer-to-have-been-called-times",
    source: "jest",
    category: "style",
  },
  "prefer-to-have-length": { ruleName: "prefer-to-have-length", source: "jest", category: "style" },
  "prefer-todo": { ruleName: "prefer-todo", source: "jest", category: "style" },
  "prefer-top-level-await": {
    ruleName: "prefer-top-level-await",
    source: "unicorn",
    category: "pedantic",
  },
  "prefer-type-error": { ruleName: "prefer-type-error", source: "unicorn", category: "pedantic" },
  "prefer-unique-test-matchers": {
    ruleName: "prefer-unique-test-matchers",
    source: "oxc",
    category: "nursery",
  },
  "prefer-use-alias": { ruleName: "prefer-use-alias", source: "oxc", category: "nursery" },
  "prefer-valid-globals": {
    ruleName: "prefer-valid-globals",
    source: "eslint",
    category: "pedantic",
  },
  "prefer-void": { ruleName: "prefer-void", source: "oxc", category: "nursery" },
  "prefer-bigint-literals": {
    ruleName: "prefer-bigint-literals",
    source: "unicorn",
    category: "style",
  },
  "preserve-caught-error": {
    ruleName: "preserve-caught-error",
    source: "eslint",
    category: "suspicious",
  },
  "prompt-error": { ruleName: "prompt-error", source: "oxc", category: "nursery" },
  "property-equality": { ruleName: "property-equality", source: "oxc", category: "nursery" },
  "provide-invalid-variadic-argument": {
    ruleName: "provide-invalid-variadic-argument",
    source: "oxc",
    category: "nursery",
  },
  radix: { ruleName: "radix", source: "eslint", category: "pedantic" },
  "raw-script-jsx-no-unclosed-script": {
    ruleName: "raw-script-jsx-no-unclosed-script",
    source: "oxc",
    category: "nursery",
  },
  "react-in-jsx-scope": { ruleName: "react-in-jsx-scope", source: "react", category: "suspicious" },
  "react-jsx-no-comment-textnodes": {
    ruleName: "react-jsx-no-comment-textnodes",
    source: "oxc",
    category: "nursery",
  },
  "react-jsx-no-duplicate-props": {
    ruleName: "react-jsx-no-duplicate-props",
    source: "oxc",
    category: "nursery",
  },
  "react-jsx-no-script-url": {
    ruleName: "react-jsx-no-script-url",
    source: "oxc",
    category: "nursery",
  },
  "react-jsx-no-target-blank": {
    ruleName: "react-jsx-no-target-blank",
    source: "oxc",
    category: "nursery",
  },
  "react-jsx-no-undef": { ruleName: "react-jsx-no-undef", source: "oxc", category: "nursery" },
  "react-jsx-use-fragment": {
    ruleName: "react-jsx-use-fragment",
    source: "oxc",
    category: "nursery",
  },
  "react/jsx-key": { ruleName: "jsx-key", source: "react", category: "correctness" },
  "react/no-namespace": { ruleName: "no-namespace", source: "react", category: "suspicious" },
  "react/no-set-state": { ruleName: "no-set-state", source: "react", category: "style" },
  "react/require-render-return": {
    ruleName: "require-render-return",
    source: "react",
    category: "nursery",
  },
  "react/rules-of-hooks": { ruleName: "rules-of-hooks", source: "react", category: "pedantic" },
  "readonly-return": { ruleName: "readonly-return", source: "oxc", category: "nursery" },
  "redundant-alt-attr": { ruleName: "redundant-alt-attr", source: "oxc", category: "nursery" },
  "relative-url-style": { ruleName: "relative-url-style", source: "unicorn", category: "style" },
  "require-array-join-separator": {
    ruleName: "require-array-join-separator",
    source: "unicorn",
    category: "style",
  },
  "require-await": { ruleName: "require-await", source: "eslint", category: "pedantic" },

  "require-array-sort-compare": {
    ruleName: "require-array-sort-compare",
    source: "typescript",
    category: "correctness",
  },
  "require-default-export": {
    ruleName: "require-default-export",
    source: "vue",
    category: "suspicious",
  },
  "require-hook": { ruleName: "require-hook", source: "jest", category: "style" },
  "require-import": { ruleName: "require-import", source: "oxc", category: "nursery" },
  "require-local-test-context-for-concurrent-snapshots": {
    ruleName: "require-local-test-context-for-concurrent-snapshots",
    source: "vitest",
    category: "correctness",
  },
  "require-mock-type-parameters": {
    ruleName: "require-mock-type-parameters",
    source: "vitest",
    category: "correctness",
  },
  "require-number-to-fixed-digits-argument": {
    ruleName: "require-number-to-fixed-digits-argument",
    source: "unicorn",
    category: "pedantic",
  },
  "require-param": { ruleName: "require-param", source: "jsdoc", category: "pedantic" },
  "require-param-description": {
    ruleName: "require-param-description",
    source: "jsdoc",
    category: "pedantic",
  },
  "require-param-name": { ruleName: "require-param-name", source: "jsdoc", category: "pedantic" },
  "require-param-type": { ruleName: "require-param-type", source: "jsdoc", category: "pedantic" },
  "require-property": { ruleName: "require-property", source: "jsdoc", category: "correctness" },
  "require-property-description": {
    ruleName: "require-property-description",
    source: "jsdoc",
    category: "correctness",
  },
  "require-property-name": {
    ruleName: "require-property-name",
    source: "jsdoc",
    category: "correctness",
  },
  "require-property-type": {
    ruleName: "require-property-type",
    source: "jsdoc",
    category: "correctness",
  },
  "require-react-root": { ruleName: "require-react-root", source: "oxc", category: "nursery" },
  "require-return": { ruleName: "require-return", source: "oxc", category: "nursery" },
  "require-return-await": { ruleName: "require-return-await", source: "oxc", category: "nursery" },
  "require-returns": { ruleName: "require-returns", source: "jsdoc", category: "pedantic" },
  "require-returns-description": {
    ruleName: "require-returns-description",
    source: "jsdoc",
    category: "pedantic",
  },
  "require-returns-type": {
    ruleName: "require-returns-type",
    source: "jsdoc",
    category: "pedantic",
  },
  "require-scaled-image": { ruleName: "require-scaled-image", source: "oxc", category: "nursery" },
  "require-test-timeout": {
    ruleName: "require-test-timeout",
    source: "vitest",
    category: "restriction",
  },
  "require-throw": { ruleName: "require-throw", source: "oxc", category: "nursery" },
  "require-to-throw-message": {
    ruleName: "require-to-throw-message",
    source: "jest",
    category: "correctness",
  },
  "require-top-level-describe": {
    ruleName: "require-top-level-describe",
    source: "jest",
    category: "style",
  },
  "require-typed-ref": { ruleName: "require-typed-ref", source: "vue", category: "style" },
  "require-unknown-property": {
    ruleName: "require-unknown-property",
    source: "oxc",
    category: "nursery",
  },
  "require-yield": { ruleName: "require-yield", source: "eslint", category: "correctness" },
  "require-yields": { ruleName: "require-yields", source: "jsdoc", category: "correctness" },
  resreq: { ruleName: "resreq", source: "oxc", category: "nursery" },
  "restrict-plus-operands": {
    ruleName: "restrict-plus-operands",
    source: "typescript",
    category: "pedantic",
  },
  "restrict-template-expressions": {
    ruleName: "restrict-template-expressions",
    source: "typescript",
    category: "correctness",
  },
  "return-await": { ruleName: "return-await", source: "typescript", category: "pedantic" },
  "return-in-finally": { ruleName: "return-in-finally", source: "oxc", category: "nursery" },
  "role-has-required-aria-props": {
    ruleName: "role-has-required-aria-props",
    source: "jsx_a11y",
    category: "correctness",
  },
  "role-supports-aria-props": {
    ruleName: "role-supports-aria-props",
    source: "jsx_a11y",
    category: "correctness",
  },
  "rules-of-hooks": { ruleName: "rules-of-hooks", source: "react", category: "pedantic" },
  "rxjs-no-ignored-observable": {
    ruleName: "rxjs-no-ignored-observable",
    source: "oxc",
    category: "nursery",
  },
  "rxjs-no-subject-unsubscribe": {
    ruleName: "rxjs-no-subject-unsubscribe",
    source: "oxc",
    category: "nursery",
  },
  "rxjs-no-unsafe-subject-next": {
    ruleName: "rxjs-no-unsafe-subject-next",
    source: "oxc",
    category: "nursery",
  },
  "rxjs-no-subject-value": {
    ruleName: "rxjs-no-subject-value",
    source: "oxc",
    category: "nursery",
  },
  "rxjs-no-unsafe-first": { ruleName: "rxjs-no-unsafe-first", source: "oxc", category: "nursery" },
  scope: { ruleName: "scope", source: "jsx_a11y", category: "correctness" },
  "script-url-quotes": { ruleName: "script-url-quotes", source: "html", category: "correctness" },
  "self-closing-comp": { ruleName: "self-closing-comp", source: "react", category: "style" },
  "self-closing-onvx、少": {
    ruleName: "self-closing-onvx、少",
    source: "oxc",
    category: "nursery",
  },
  semi: { ruleName: "semi", source: "eslint", category: "style" },
  "semi-style": { ruleName: "semi-style", source: "eslint", category: "style" },
  "serde-export-name": { ruleName: "serde-export-name", source: "oxc", category: "nursery" },
  "sharedprop-name": { ruleName: "sharedprop-name", source: "oxc", category: "nursery" },
  "side-effect-in-babel-hooks": {
    ruleName: "side-effect-in-babel-hooks",
    source: "oxc",
    category: "nursery",
  },
  "simplifiable-comparison": {
    ruleName: "simplifiable-comparison",
    source: "oxc",
    category: "nursery",
  },
  "single-var-declarator": {
    ruleName: "single-var-declarator",
    source: "eslint",
    category: "style",
  },
  slash三五: { ruleName: "slash三五", source: "oxc", category: "nursery" },
  "sort-imports": { ruleName: "sort-imports", source: "eslint", category: "style" },
  "sort-keys": { ruleName: "sort-keys", source: "eslint", category: "style" },
  "sort-vars": { ruleName: "sort-vars", source: "eslint", category: "pedantic" },
  "spec-only": { ruleName: "spec-only", source: "promise", category: "restriction" },
  "spread-in-callbacks": { ruleName: "spread-in-callbacks", source: "oxc", category: "nursery" },
  "stable-sort": { ruleName: "stable-sort", source: "oxc", category: "nursery" },
  "state-in-constructor": { ruleName: "state-in-constructor", source: "react", category: "style" },
  "static-semantics": { ruleName: "static-semantics", source: "oxc", category: "nursery" },
  "strict-boolean-expressions": {
    ruleName: "strict-boolean-expressions",
    source: "typescript",
    category: "pedantic",
  },
  "strict-case": { ruleName: "strict-case", source: "oxc", category: "nursery" },
  "strict-comparison": { ruleName: "strict-comparison", source: "oxc", category: "nursery" },
  "strict-mode": { ruleName: "strict-mode", source: "oxc", category: "nursery" },
  "strict-void-return": {
    ruleName: "strict-void-return",
    source: "typescript",
    category: "nursery",
  },
  "style-prop-object": { ruleName: "style-prop-object", source: "react", category: "suspicious" },
  "switch-case-braces": { ruleName: "switch-case-braces", source: "eslint", category: "style" },
  "switch-effect": { ruleName: "switch-effect", source: "oxc", category: "nursery" },
  "switch-no-default": { ruleName: "switch-no-default", source: "oxc", category: "nursery" },
  "symbol-description": { ruleName: "symbol-description", source: "eslint", category: "pedantic" },
  "system-deprecated": { ruleName: "system-deprecated", source: "oxc", category: "nursery" },
  "system-extraneous": { ruleName: "system-extraneous", source: "oxc", category: "nursery" },
  "system-missing-fields": {
    ruleName: "system-missing-fields",
    source: "oxc",
    category: "nursery",
  },
  "system-no-outside": { ruleName: "system-no-outside", source: "oxc", category: "nursery" },
  "system-props": { ruleName: "system-props", source: "oxc", category: "nursery" },
  "tabindex-no-positive": {
    ruleName: "tabindex-no-positive",
    source: "jsx_a11y",
    category: "correctness",
  },
  "template-angle-bracket": {
    ruleName: "template-angle-bracket",
    source: "eslint",
    category: "style",
  },
  "template-curly-in-string": {
    ruleName: "template-curly-in-string",
    source: "eslint",
    category: "style",
  },
  "test-const": { ruleName: "test-const", source: "oxc", category: "nursery" },
  "test-equality": { ruleName: "test-equality", source: "oxc", category: "nursery" },
  "test-no-only": { ruleName: "test-no-only", source: "oxc", category: "nursery" },
  "text-encoding-identifier-case": {
    ruleName: "text-encoding-identifier-case",
    source: "unicorn",
    category: "style",
  },
  "this-in-callbacks": { ruleName: "this-in-callbacks", source: "oxc", category: "nursery" },
  "throw-in-finally": { ruleName: "throw-in-finally", source: "oxc", category: "nursery" },
  "throw-new-error": { ruleName: "throw-new-error", source: "unicorn", category: "style" },
  "title-case": { ruleName: "title-case", source: "html", category: "style" },
  "triple-slash-reference": {
    ruleName: "triple-slash-reference",
    source: "typescript",
    category: "correctness",
  },
  "ts-ident": { ruleName: "ts-ident", source: "oxc", category: "nursery" },
  "type-declaration-implicitly-any": {
    ruleName: "type-declaration-implicitly-any",
    source: "oxc",
    category: "nursery",
  },
  "type-no-unknown": { ruleName: "type-no-unknown", source: "oxc", category: "nursery" },
  "unbound-method": { ruleName: "unbound-method", source: "typescript", category: "correctness" },
  "unclosed-system": { ruleName: "unclosed-system", source: "oxc", category: "nursery" },
  "uncomparable-el-if": { ruleName: "uncomparable-el-if", source: "oxc", category: "nursery" },
  "unconditional-break": { ruleName: "unconditional-break", source: "oxc", category: "nursery" },
  "unconditional-continue": {
    ruleName: "unconditional-continue",
    source: "oxc",
    category: "nursery",
  },
  "unconditional-return": { ruleName: "unconditional-return", source: "oxc", category: "nursery" },
  "unified-signatures": { ruleName: "unified-signatures", source: "typescript", category: "style" },
  "uninvoked-array-callback": {
    ruleName: "uninvoked-array-callback",
    source: "oxc",
    category: "correctness",
  },
  "unknown-prototype": { ruleName: "unknown-prototype", source: "oxc", category: "nursery" },
  "unlabeled-blocks": { ruleName: "unlabeled-blocks", source: "oxc", category: "nursery" },
  unreachable: { ruleName: "unreachable", source: "oxc", category: "nursery" },
  "unsafe-negative-arguments": {
    ruleName: "unsafe-negative-arguments",
    source: "oxc",
    category: "nursery",
  },
  "unsafe-negation": { ruleName: "unsafe-negation", source: "eslint", category: "correctness" },
  "unsafe-optional-chaining": {
    ruleName: "unsafe-optional-chaining",
    source: "eslint",
    category: "correctness",
  },
  "unused-imports": { ruleName: "unused-imports", source: "oxc", category: "nursery" },
  "unused-ids": { ruleName: "unused-ids", source: "oxc", category: "nursery" },
  "use-alias": { ruleName: "use-alias", source: "oxc", category: "nursery" },
  "use-biome-jsx-keys": { ruleName: "use-biome-jsx-keys", source: "oxc", category: "nursery" },
  "use-default-parameter": {
    ruleName: "use-default-parameter",
    source: "oxc",
    category: "nursery",
  },
  "use-element-type": { ruleName: "use-element-type", source: "oxc", category: "nursery" },
  "use-fallback-type": { ruleName: "use-fallback-type", source: "oxc", category: "nursery" },
  "use-grouped-type-import": {
    ruleName: "use-grouped-type-import",
    source: "oxc",
    category: "nursery",
  },
  "use-isnan": { ruleName: "use-isnan", source: "eslint", category: "correctness" },
  "use-named-reference": { ruleName: "use-named-reference", source: "oxc", category: "nursery" },
  "use-node-protocol": { ruleName: "use-node-protocol", source: "oxc", category: "nursery" },
  "use-optional-catch-binding": {
    ruleName: "use-optional-catch-binding",
    source: "oxc",
    category: "nursery",
  },
  "use-shorthand-array-type": {
    ruleName: "use-shorthand-array-type",
    source: "oxc",
    category: "nursery",
  },
  "use-shorthand-type": { ruleName: "use-shorthand-type", source: "oxc", category: "nursery" },
  "use-strict-preference": {
    ruleName: "use-strict-preference",
    source: "oxc",
    category: "nursery",
  },
  "use-type-alias": { ruleName: "use-type-alias", source: "oxc", category: "nursery" },
  "use-unknown-in-catch-callback-variable": {
    ruleName: "use-unknown-in-catch-callback-variable",
    source: "typescript",
    category: "restriction",
  },
  "use-win32-registry": { ruleName: "use-win32-registry", source: "oxc", category: "nursery" },
  "valid-define-emits": { ruleName: "valid-define-emits", source: "vue", category: "correctness" },
  "valid-define-props": { ruleName: "valid-define-props", source: "vue", category: "correctness" },
  "valid-describe-callback": {
    ruleName: "valid-describe-callback",
    source: "jest",
    category: "correctness",
  },
  "valid-expect": { ruleName: "valid-expect", source: "jest", category: "correctness" },
  "valid-groupid": { ruleName: "valid-groupid", source: "oxc", category: "nursery" },
  "valid-id": { ruleName: "valid-id", source: "html", category: "correctness" },
  "valid-lang": { ruleName: "valid-lang", source: "html", category: "correctness" },
  "valid-link-text": { ruleName: "valid-link-text", source: "oxc", category: "nursery" },
  "valid-name": { ruleName: "valid-name", source: "oxc", category: "nursery" },
  "valid-param": { ruleName: "valid-param", source: "oxc", category: "nursery" },
  "valid-params": { ruleName: "valid-params", source: "promise", category: "correctness" },
  "valid-title": { ruleName: "valid-title", source: "jest", category: "correctness" },
  "valid-typeof": { ruleName: "valid-typeof", source: "eslint", category: "correctness" },
  "value-affected-by-writable": {
    ruleName: "value-affected-by-writable",
    source: "oxc",
    category: "nursery",
  },
  "vars-on-top": { ruleName: "vars-on-top", source: "eslint", category: "style" },
  "void-dom-elements-no-children": {
    ruleName: "void-dom-elements-no-children",
    source: "react",
    category: "correctness",
  },
  "void-use-result": { ruleName: "void-use-result", source: "oxc", category: "nursery" },
  "warn-on-inline-comments": {
    ruleName: "warn-on-inline-comments",
    source: "oxc",
    category: "nursery",
  },
  "warn-todo": { ruleName: "warn-todo", source: "vitest", category: "correctness" },
  "webpack-loader-syntax": {
    ruleName: "webpack-loader-syntax",
    source: "oxc",
    category: "nursery",
  },
  "wildcard-style": { ruleName: "wildcard-style", source: "oxc", category: "nursery" },
  "with-env": { ruleName: "with-env", source: "oxc", category: "nursery" },
  yoda: { ruleName: "yoda", source: "eslint", category: "style" },
};
